### ISSUE TITLE
BUG: milestone is not checked

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/action-check-changelogfile#7]
The presence of a milestone should still be checked, isn't it?

<img width="1280" alt="Screenshot 2023-07-25 at 12 59 51" src="https://github.com/scientific-python/action-check-changelogfile/assets/6788290/91c0a26e-cf40-4b1d-8ba6-ee9898067b03">

**Comment by pllim** [comment]
I don't think it is a bug. This is a change log checker, not a milestone checker. It only check for milestone if entry is present to make sure the entry matches the milestone.

We used to have separate astropy-bot just for milestone check (independent of change log) so that went away when the bot got killed by Heroku. Now with Actions, there is a long standing request for PR to emit milestone event but for reason I do not understand, GitHub simply does not care; see that milestone is not listed under https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

**Comment by bsipocz** [comment]
Ahh, gotcha. Well, if it's not a bug here, it's definitely a missing feature from GH :) (But then I suppose some combination with Lars' milestone action could eventually work nicely).

**Comment by bsipocz** [comment]
OK, indeed it's nicely checks the consistency, which is great. https://github.com/astropy/pyvo/actions/runs/5662110303/job/15341399802#step:3:9

```
Changelog entry section (1.4.2) inconsistent with milestone (1.5).
```

OTOH, rc versions are not valid? 

```
 WARNING: Invalid version string: 0.7rc1 (2018-02-18)
 ```

**Comment by pllim** [comment]
I don't think we ever considered the possibility of people using RC tag as final section header. Do we have a use case for that? I thought RC or not, the change log should list the final release number?

**Comment by bsipocz** [comment]
Yeah, but apparently for pyvo there are 0.7rc1 and 0.7rc2 on pypi and then a 0.8. And in the changelog a 0.7rc1 then 0.8. 
These are pretty ancient releases, so we either take them as is and accept rc in the changelog, or I do a correctional 0.7 release just off of 0.7rc2 and do a correction to the changelog, too. I don't really have a strong preference either way.

**Comment by pllim** [comment]
Re: pyvo -- Weird, how did 0.7 not make it past RC, and then skip straight to 0.8? Do you have any users that somehow need the 0.7 proper release?

The purist in me say pyvo should fix the botched 0.7 release (or at the very least not list RC in change log). But that said, I don't think making the section header check more flexible is a bad thing. However, for the latter, #3 has to happen first.

I'll let you decide since your workload on pyvo is affected by the decision here.

**Comment by bsipocz** [comment]
> Do you have any users that somehow need the 0.7 proper release

No, it was back in 2018, so that water doesn't even remember any bridges. The changelog was in some state and I did a lot of historical correction, but didn't want to change the actual release names.
Doing a 0.7 release, 5 years after that fact, just to make the changelog consistent with version naming feels a bit overkill, but it doesn't take much time to cut a release, so I could do that (though the pypi date will be way off, so I'm not sure it's such a big improvement of the state anyway)

**Comment by bsipocz** [comment]
> However, for the latter, https://github.com/scientific-python/action-check-changelogfile/issues/3 has to happen first

I can live with it. After all it's just a warning 😅

**Comment by pllim** [comment]
Yeah, I agree releasing 0.7 now is pointless. Now that you opened #8, can we close this issue?

**Comment by bsipocz** [comment]
Well, let's close it as an unfixable, but open it back up once milestoning become action trigger events. E.g. it's a bit annoying to get the red cross once one fixed the milestone for the changelog, or to have a green when there is changelog but without a milestone.

**Comment by pllim** [comment]
Definitely. Thanks!

I have been waiting for GitHub to fix it for years though. 😿
